[project]
name = "doctor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.116.1",
    "openai-agents>=0.3.2",
    "pymongo>=4.14.1",
]
